### ISSUE TITLE
error: 'user_regs_struct' object has no attribute 'gpr0'

### ISSUE THREAD

**Issue by doomedraven** [haypo/python-ptrace#40]
Hello i having weird error, 
but I can see it in https://github.com/haypo/python-ptrace/blob/master/ptrace/binding/linux_struct.py#L16

any idea? is the 0.9.2 version installed with easy_install

Thanks

**Comment by haypo** [comment]
What is your CPU? Maybe CPU_PPC32 check is not correct? The check is:

```
CPU_PPC32 = (os.uname()[4] == 'ppc')
```

Can you please also paste your uname: UNIX uname command, or result of Python os.uname().

**Comment by doomedraven** [comment]
oh it's ppc64, closing, as that is not supported arch no?

**Comment by haypo** [comment]
> oh it's ppc64, closing, as that is not supported arch no?

It's supported as soon as someone writes a patch to support it :-)

**Comment by doomedraven** [comment]
good one, i see in https://github.com/haypo/python-ptrace/blob/master/ptrace/cpu_info.py

```
CPU_PPC64 = (_machine == 'ppc64')
CPU_POWERPC = (CPU_PPC32 or CPU_PPC64)
```

and i would only need to extend the asm registers for ppc64 or something else?

**Comment by haypo** [comment]
> i would only need to extend the asm registers for ppc64 or something else?

Hard to say, I wrote python-ptrace a long time ago and I don't recall all subtle details :-) Start by adding registers, yeah.

It depends also on the support level that you want. For example, do you want to support breakpoints? Support parsing syscalls?

**Comment by doomedraven** [comment]
everything better for sure :)
