### ISSUE TITLE
FAIL: test_open (test_strace.TestStrace)

### ISSUE THREAD

**Issue by mimi1vx** [haypo/python-ptrace#42]
When building on openSUSE:Tumbleweed build fails in testsuite:

https://build.opensuse.org/public/build/openSUSE:Factory/standard/x86_64/python-python-ptrace/_log

[_log.txt](https://github.com/haypo/python-ptrace/files/1311119/_log.txt)

**Comment by haypo** [comment]
Would you mind to test the commit 5fdd17949add0234fe71c87112c6453a4617708a which should fix the issue? If it works, I can do a proper release.

**Comment by mimi1vx** [comment]
@haypo works like charm

**Comment by haypo** [comment]
I released python-ptrace 0.9.3. Enjoy!
